#include "exceptions.hpp"

using namespace std;

void Logic_Exception::print_error()
{
	cout << error_message; 
}